paginate: 5
paginate_path: "blog/:num/"
blog_name: The CloudCannon Blog
blog_description: The CloudCannon Blog
site_url: http://cloudcannon.com
collections:
  press:
    name: Featured Articles
    output: false
  milestones:
    name: Milestones
    output: false
